const int LEDs[] = {3,4,5,8,9,10,11,12};
int i;
int j=0;

void setup()
{
  for(i=0;i<8;i++)
    {
       pinMode(LEDs[i],OUTPUT);
    }
}
void loop()
{
  for(i=0;i<8;i++)
   {
     digitalWrite(LEDs[i],HIGH);
   }
  delay(100);
  for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],LOW);
  }
  delay(100);
  for(i=0;i<8;i++)
   {
     digitalWrite(LEDs[i],HIGH);
   }
  delay(100);
  for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],LOW);
  }
  delay(100);
  
  for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }
   for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  } for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  } for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  } for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  } for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  } for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }
  for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }
  for(i=0;i<8;i++)
   {
     digitalWrite(LEDs[i],HIGH);
   }
  delay(100);
  for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],LOW);
  }
  delay(100);
  for(i=0;i<8;i++)
   {
     digitalWrite(LEDs[i],HIGH);
   }
  delay(100);
  for(i=0;i<8;i++)
  {
    digitalWrite(LEDs[i],LOW);
  }
  delay(100);
  for(i=7;i>=0;i--)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }
  for(i=7;i>=0;i--)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }for(i=7;i>=0;i--)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }for(i=7;i>=0;i--)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }for(i=7;i>=0;i--)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }for(i=7;i>=0;i--)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }for(i=7;i>=0;i--)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }for(i=7;i>=0;i--)
  {
    digitalWrite(LEDs[i],HIGH);
    delay(100);
    digitalWrite(LEDs[i],LOW);
  }
}
